version: "3.8"

services:
  # The leftmost are the services provided by this composition of docker containers
  tracking:
    # The service app runs the COMMAND by default if no other command is given
    command: rosrun object_detection segmentation.py
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: host
    volumes:
      - ./:/app/src/segmentation/
      - ./docker/bin:/app/bin/
      # Allow access to the display socket for sending graphics data
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      # Allow access to the default camera (Change integer to switch camera)
      - /dev/video0:/dev/video0
    environment:
      # Use the same display as the host (Change integer to switch display)
      - DISPLAY=${DISPLAY}